version: '3'

services:
  backend:
    build:
      context: ./physio_backend
    container_name: physio_backend
    ports:
      - "8000:8000"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  frontend:
    build:
      context: ./physio_frontend
    container_name: physio_frontend
    ports:
      - "5000:5000"
    depends_on:
      backend:
        condition: service_healthy
    environment:
      - BACKEND_URL=http://backend:8000